// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/prijava": {
    params: {};
  };
  "/admin": {
    params: {};
  };
  "/profil": {
    params: {};
  };
  "/matching": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/prijava" | "/admin" | "/profil" | "/matching";
  };
  "../pages/Home.tsx": {
    id: "../pages/Home";
    page: "/";
  };
  "../pages/FormPage.tsx": {
    id: "../pages/FormPage";
    page: "/prijava";
  };
  "../pages/AdminDashboard.tsx": {
    id: "../pages/AdminDashboard";
    page: "/admin";
  };
  "../pages/ProfilePage.tsx": {
    id: "../pages/ProfilePage";
    page: "/profil";
  };
  "../pages/MatchingPage.tsx": {
    id: "../pages/MatchingPage";
    page: "/matching";
  };
};

type RouteModules = {
  "root": typeof import("./src/app/root.tsx");
  "../pages/Home": unknown;
  "../pages/FormPage": unknown;
  "../pages/AdminDashboard": unknown;
  "../pages/ProfilePage": unknown;
  "../pages/MatchingPage": unknown;
};