// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/prijava": {
    params: {};
  };
  "/admin": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/prijava" | "/admin";
  };
  "../pages/Home.tsx": {
    id: "../pages/Home";
    page: "/";
  };
  "../pages/FormPage.tsx": {
    id: "../pages/FormPage";
    page: "/prijava";
  };
  "../pages/AdminDashboard.tsx": {
    id: "../pages/AdminDashboard";
    page: "/admin";
  };
};

type RouteModules = {
  "root": typeof import("./src/app/root.tsx");
  "../pages/Home": unknown;
  "../pages/FormPage": unknown;
  "../pages/AdminDashboard": unknown;
};